Repository elca-hub/hackit_2024, pull requests merged in 2024-03, with the labels that each got.

#3 Userの生成
  back/Dockerfile
  back/Gemfile
  back/Gemfile.lock
  back/app/controllers/users_controller.rb
  back/app/models/user.rb
  back/bin/render-build.sh
  back/config/database.yml
  back/config/routes.rb
  back/db/migrate/20240311070816_create_users.rb
  compose.yml
Labels: バックエンド/rails

#9 ホーム画面の作成
  front/app/layout.tsx
  front/app/page.tsx
  front/app/providers.tsx
  front/package-lock.json
  front/package.json
Labels: フロントエンド/next.js

#11 ログインページの作成
  front/app/layout.tsx
  front/app/login/page.tsx
  front/package-lock.json
  front/package.json
Labels: フロントエンド/next.js

#13 deviseを用いたユーザのログイン・新規登録APIの本格実装
  back/app/models/user.rb
  back/config/environments/development.rb
  back/config/environments/test.rb
  back/config/initializers/cors.rb
  back/config/initializers/devise_token_auth.rb
  back/config/initializers/wrap_parameters.rb
  front/app/login/page.tsx
  swagger/openapi.yaml
Labels: バックエンド/rails, フロントエンド/next.js

#15 新規登録ページの作成
  back/Gemfile
  back/Gemfile.lock
  back/app/controllers/application_controller.rb
  back/app/controllers/part_time_color_controller.rb
  back/app/controllers/part_times_controller.rb
  back/app/controllers/shift_controller.rb
  back/app/controllers/v1/auth/registrations_controller.rb
  back/app/controllers/v1/auth/sessions_controller.rb
  back/app/models/part_time.rb
  back/app/models/part_time_color.rb
  back/app/models/shift.rb
  back/config/routes.rb
  back/db/migrate/20240314031226_create_shifts.rb
  back/db/migrate/20240314040225_add_part_time_id_to_part_times.rb
  back/db/migrate/20240314045240_change_data_time_allowance_start_to_part_times.rb
  back/db/migrate/20240314045856_add_reference_user_to_part_time.rb
  back/db/migrate/20240314050701_add_reference_part_time_color_to_part_time.rb
  back/db/migrate/20240314071256_add_job_id_to_part_times.rb
  back/db/migrate/20240314184830_add_user_column_goal_annual_income.rb
  back/db/schema.rb
  back/db/seeds.rb
  front/app/login/page.tsx
  front/app/page.tsx
  front/app/register/page.tsx
  front/app/register/steps/CheckValueStep.tsx
  front/app/register/steps/GoalAnnualIncomeStep.tsx
  front/app/register/steps/userInfoStep.tsx
  swagger/openapi.yaml
Labels: バックエンド/rails, フロントエンド/next.js

#16 APIサーバのホスト名を環境変数として保存
  doc/how-to-use.md
  front/app/login/page.tsx
  front/app/register/steps/CheckValueStep.tsx
Labels: フロントエンド/next.js

#18 Rails/add/gacha
  back/app/controllers/gachas_controller.rb
  back/app/controllers/shifts_controller.rb
  back/app/models/gacha.rb
  back/app/models/part_time.rb
  back/app/models/shift.rb
  back/app/models/user.rb
  back/config/routes.rb
  back/db/migrate/20240312154405_devise_token_auth_create_users.rb
  back/db/migrate/20240315140847_remove_job_id_from_part_times.rb
  back/db/migrate/20240315143607_create_gachas.rb
  back/db/migrate/20240315154401_add_goal_monthly_income_to_users.rb
  back/db/migrate/20240315165928_add_user_id_to_gachas.rb
  back/db/schema.rb
Labels: バックエンド/rails
